#!/bin/sh

# Modules
apm install atom-ternjs
apm install atom-beautify
apm install autocomplete-modules
apm install color-picker
apm install git-plus
apm install file-icons
apm install highlight-selected
apm install linter
apm install linter-eslint
apm install linter-sass-lint
apm install nuclide
apm install project-manager
apm install simple-drag-drop-text
apm install vim-mode
