#!/bin/sh

# Vim necessities
sudo npm install -g appium
sudo npm install -g babel-eslint
sudo npm install -g csslint
sudo npm install -g eslint-plugin-react@2.7.1
sudo npm install -g eslint@0.20.0
sudo npm install -g js-beautify
sudo npm install -g jscs@1.13.1
sudo npm install -g jshint
sudo npm install -g jsonlint
sudo npm install -g jsonlint
sudo npm install -g n
sudo npm install -g node-inspector
sudo npm install -g npm-check

# List
npm list -g --depth=0
