#!/bin/sh

# Assumes node > 8.7.0

# Vim necessities
sudo npm install -g babel-eslint@8
sudo npm install -g eslint@4.x
sudo npm install -g sass-lint@latest
sudo npm install -g csslint@latest
sudo npm install -g jsonlint@latest
sudo npm install -g js-beautify@latest
sudo npm install -g npm-check@latest
sudo npm install -g typescript@latest
sudo npm install -g yo@latest

# List
npm list -g --depth=0